# Generated by Django 4.1 on 2022-08-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_register_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='age',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
        migrations.AddField(
            model_name='register_table',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
