# Generated by Django 4.1 on 2022-08-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_register_table_age_register_table_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_table',
            name='age',
            field=models.CharField(blank=True, default='Male', max_length=250, null=True),
        ),
    ]
