# Generated by Django 4.1 on 2022-08-17 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0006_alter_register_table_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=250)),
                ('form_image', models.ImageField(upload_to='upload')),
                ('details', models.TextField()),
                ('form_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.category')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
